### PR TITLE
Adding samplers and loss weight implementation on arXiv:2401.13162

### PR DESCRIPTION
**Pull request by chengjiang123**
Hello Oz!

Hope this contribution can be helpful for the CaloDiffusion project.

The samplers (restart, UniPC, LMS, EDM_g++ (in progress)), some noise scheduler functions, and new loss function both based on the old/new code styles are included here. I did not manage to run successfully with ControlNet. Probably need further modification to catch up with newest code. Also, one thing worth mentioning is that we requested an update for the Calochallenge, finally including the log posterior evaluation for the public.
Please let me know if anything should be corrected or redundant. Thank you again for cleaning up the repo :)

All the best,
Cheng Jiang

### CODE REVIEW

**Comment by OzAmram** [comment]
Hi Cheng!

Thanks a lot for this PR! 

So a lot of the modifications are in this new `CaloDiffusion_old.py` file. Was this because you weren't able to integrate with some of the recent changes in the regular `CaloDiffusion.py`? It would be ideal to have everything in one file

**Comment by chengjiang123** [comment]
Yes! That file is based on the old CaloDiffusion code style. There is a lot of replication with the current one. But should be able to run without layer cond and ControlNet. I am trying to integrate all the newest changes so that it could be much more convenient and readable. The changes in other two files is based on the most recent changes. I will keep updating the codes in the following weeks! Thank you so much for the comments :)

**Comment by chengjiang123** [comment]
That's great! I will certainly concentrate on incorporating the layer conditioning into the project. Really appreciate your guidance again.

**Comment by OzAmram** [comment]
I went ahead and did a refactor of some of the sampling code to be separate from the `CaloDiffuion` class which I had been meaning to do for a while. Its under the `dev` branch

It might make it somewhat easier for you to integrate your changes. Let me know if you have any feedback :)

**Comment by chengjiang123** [comment]
Thank you very much Oz :) Indeed this makes me more convenient to modify. I have changed based on the newest dev branch (might also have few file changes by the default difference between dev and main branch). Just trained a small layer diffusion based on your code today. I think most of samplers (lms,restart,dpm2) works fine now, also added minsnr weighting. I guess the dpm solver sampler is still in dev? I leave unipc implement there and should be consistent with other dpm solver samplers.

**Comment by OzAmram** [comment]
Hey! Sorry for the long silence on my end, I was away from work for a little while
I went ahead and merged the dev changes into main and fixed the small merge conflict. 
It think we should be good now, I'll test everything out tomorrow before merging
Thanks!

**Pull request merged**
